src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/lru_time_cache/9)

retireve everything in LruCache

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/lru_time_cache/11)

To update to 1.0.0-beta.2

---

appveyor.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/lru_time_cache/12)

Update to beta 3

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/lru_time_cache/13)

Standardise to travis-cargo

---

src/lib.rs

Shouldn't break existing API as these are just added functions and comments where breaking changes should happen in the future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/17)

Api additions

---

CHANGELOG.md
Cargo.toml
README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/18)

Increased version to 0.1.6

---

Cargo.toml
src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/20)

Adds `contains_key` method; Derives from Clone; Version bump

---

README.md
src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/23)

Added Waffle, GPL3 & SAFE-Approved badges 

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/27)

RUST-3 Sprint task

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/29)

using travis osx and scripts

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/30)

warning fix

---

README.md
appveyor.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/32)

Appveyor script, update readme.

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/33)

Remove add function. Fixes #16.

---

Cargo.toml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/37)

Update to Version 0.2.1

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/38)

Removes expired elements before accessing elements.

---

CHANGELOG.md
Cargo.toml
README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/39)

Version change to 0.2.2

---

src/lib.rs

**Code Bounty task**
Initial run of RustFmt on libraries that are not being worked on at the moment.
**My bitcoin address:** 1KfJGj4j8iYdywwgZGkwsVZngaSXkTX6XL
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/36)

Initial run of RustFmt

---

README.md
src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/41)

Updated lint checks and README.md.

---

CHANGELOG.md
Cargo.toml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/47)

Version change to 0.2.3

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/48)

Update deprecated item

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/50)

Remove lint and 100 character pernicketiness

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/51)

Update time for non-inplace 'value' returns.

---

CHANGELOG.md
Cargo.toml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/52)

Version change to 0.2.5

---

.travis.yml
appveyor.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/53)

Limit CI runs to stable channel.

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/55)

Allow non-Clone Value types.

---

CHANGELOG.md
Cargo.toml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/56)

Version change to 0.2.6

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/57)

Apply clippy and make len not mutate the cache.

---

src/lib.rs

Reverts maidsafe/lru_time_cache#57
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/58)

Revert "Apply clippy and make len not mutate the cache."

---

src/lib.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/60)

Apply rustfmt.

---

.travis.yml
Cargo.toml
src/lib.rs

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/62)

Add clippy and nightly for travis.

---

CHANGELOG.md
Cargo.toml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/64)

Version change to 0.2.7

---

src/lib.rs

And fix remaining Clippy warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/75)

test/peek_iter: add more unit tests for peek_iter

---

README.md
src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/lru_time_cache/78)

feat/lib: remove retrieve_all methods

---

.travis.yml
Cargo.toml
README.md
appveyor.yml
src/lib.rs

Update forum links and fix Clippy lints.

---

.travis.yml
Cargo.toml
README.md
appveyor.yml
src/lib.rs

* fixed some outdated URLs
* removed mention of a version of the Contributor Agreement
* improved AppVeyor and Travis scripts

MAID-2000: chore/all: cleanup/improve CI scripts and README

---

.travis.yml
appveyor.yml
src/lib.rs

nightly to 2018-07-07
clippy to 0.0.212
rustfmt to 0.99.2

[MAID-3107] chore/ci: update scripts to Rust stable 1.28.0

---

.travis.yml
Cargo.toml
appveyor.yml
src/lib.rs

* Upgrade compiler
* Switch to 2018 edition
* Fix compilation, fmt and clippy warnings
* Remove nightly from CI

Upgrade to rust 2018 edition

---

CHANGELOG.md
src/lib.rs

Introduces new methods that allow to collect removed expired entries.

Collect expired items

---

Cargo.toml
src/lib.rs

Upgrade to latest rand, only affects tests

upgrade rand
